# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "076b977e7728705d0cb721d5873a44ed"
name = "Unlimited Filters & Collection"
application_url = "https://shopify-unlimited-filters.vercel.app"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,unauthenticated_read_product_listings"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://shopify-unlimited-filters.vercel.app" ]
